// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoviesVotingMicroservice.Models;

namespace MoviesVotingMicroservice.Migrations
{
    [DbContext(typeof(MovieOpinionContext))]
    partial class MovieOpinionContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MoviesVotingMicroservice.Models.MovieOpinion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsPositive");

                    b.Property<int>("MovieId");

                    b.Property<DateTime>("OpinionDate");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.ToTable("MovieOpinions");
                });
#pragma warning restore 612, 618
        }
    }
}
